# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "fisk", "~> 2.3"

gem "rspec", "~> 3.11"

gem "require_relative", "~> 1.0"
